/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto__c3;

import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO
 */
public class Registrados extends javax.swing.JFrame {
javax.swing.JFrame padre;
ArrayList<Evento> lista_eventos_validar;
private DefaultTableModel table_model_eventos1;
private DefaultTableModel table_model_eventos2;
private DefaultTableModel table_model_eventos3;
    /**
     * Creates new form Registrados
     */
    public Registrados() {
        initComponents();
        configComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
    }
    public void recibir (javax.swing.JFrame padre1){
        this.padre=padre1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_infantil = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla_juvenil = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabla_mayores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(735, 660));
        setMinimumSize(new java.awt.Dimension(735, 660));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Gill Sans Ultra Bold Condensed", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TABLA DE REGISTRADOS POR CATEGORIA");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 20, 493, 37);

        tabla_infantil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_infantil);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(19, 81, 669, 117);

        tabla_juvenil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tabla_juvenil);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(19, 246, 669, 127);

        tabla_mayores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tabla_mayores);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(19, 410, 669, 123);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CATEGORIA INFANTIL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 60, 145, 16);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CATEGORIA JUVENIL");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(270, 230, 145, 16);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CATEGORIA MAYORES");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 390, 145, 15);

        cancelar.setBackground(new java.awt.Color(255, 0, 0));
        cancelar.setForeground(new java.awt.Color(255, 0, 0));
        cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/no.png"))); // NOI18N
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(cancelar);
        cancelar.setBounds(520, 550, 110, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/milky-way-2695569__340_1.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(4, 4, 710, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
      this.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton cancelar;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tabla_infantil;
    private javax.swing.JTable tabla_juvenil;
    private javax.swing.JTable tabla_mayores;
    // End of variables declaration//GEN-END:variables
private void configComponents() {
        DefaultTableModel table_model_eventos_1 = new DefaultTableModel();
        table_model_eventos_1.addColumn("id");
        table_model_eventos_1.addColumn("cedula");
        table_model_eventos_1.addColumn("nombre");
        table_model_eventos_1.addColumn("apellido");
        table_model_eventos_1.addColumn("edad");
        table_model_eventos_1.addColumn("fecha de nacimiento");
        table_model_eventos_1.addColumn("fecha de registro");
        table_model_eventos_1.addColumn("nombre de la imagen");
        table_model_eventos_1.addColumn("puntaje");
        
        DefaultTableModel table_model_eventos_2 = new DefaultTableModel();
        table_model_eventos_2.addColumn("id");
        table_model_eventos_2.addColumn("cedula");
        table_model_eventos_2.addColumn("nombre");
        table_model_eventos_2.addColumn("apellido");
        table_model_eventos_2.addColumn("edad");
        table_model_eventos_2.addColumn("fecha de nacimiento");
        table_model_eventos_2.addColumn("fecha de registro");
        table_model_eventos_2.addColumn("nombre de la imagen");
        table_model_eventos_2.addColumn("puntaje");
        
        DefaultTableModel table_model_eventos_3 = new DefaultTableModel();
        table_model_eventos_3.addColumn("id");
        table_model_eventos_3.addColumn("cedula");
        table_model_eventos_3.addColumn("nombre");
        table_model_eventos_3.addColumn("apellido");
        table_model_eventos_3.addColumn("edad");
        table_model_eventos_3.addColumn("fecha de nacimiento");
        table_model_eventos_3.addColumn("fecha de registro");
        table_model_eventos_3.addColumn("nombre de la imagen");
        table_model_eventos_3.addColumn("puntaje");

        tabla_infantil.setModel(table_model_eventos_1);
        tabla_juvenil.setModel(table_model_eventos_2);
        tabla_mayores.setModel(table_model_eventos_3);
        setTableModel1(table_model_eventos_1);
        setTableModel2(table_model_eventos_2);
        setTableModel3(table_model_eventos_3);
        refreshTableModel();
      
    }
     public void setTableModel1(DefaultTableModel table_model_eventos){
        this.table_model_eventos1 = table_model_eventos;//recibe el modelo de la tabla de eventos
    }
    public void setTableModel2(DefaultTableModel table_model_eventos){
        this.table_model_eventos2 = table_model_eventos;//recibe el modelo de la tabla de eventos
    }
    public void setTableModel3(DefaultTableModel table_model_eventos){
        this.table_model_eventos3 = table_model_eventos;//recibe el modelo de la tabla de eventos
    }
   public void refreshTableModel()
    {
        //metodo que actualisa la tabla despues de ser agregaado un evento
        ArrayList<Evento> lista_eventos = Repositorio1.obtenerTodos();
        lista_eventos_validar=lista_eventos;
       // ArrayList<Evento> infantil;
        //ArrayList<Evento> juvenil;
        //ArrayList<Evento> mayor;
        while (table_model_eventos1.getRowCount() > 0) {
            table_model_eventos1.removeRow(0);
        }
        while (table_model_eventos2.getRowCount() > 0) {
            table_model_eventos2.removeRow(0);
        }
        while (table_model_eventos3.getRowCount() > 0) {
            table_model_eventos3.removeRow(0);
        }
        
        for(Evento e: lista_eventos)
        {
            if((Integer.parseInt(e.getEdad()))<=15){
               String[] data = {Integer.toString(e.getId()), e.getCedula(),e.getNombre(), e.getApellido(), e.getEdad(),e.getFechanacimiento().toString(), e.getFecharegistro().toString(), e.getNomimagen(), e.getPuntaje()}; 
               table_model_eventos1.addRow(data);
            }else if((Integer.parseInt(e.getEdad()))>15&&(Integer.parseInt(e.getEdad()))<=24){
                String[] data = {Integer.toString(e.getId()), e.getCedula(),e.getNombre(), e.getApellido(), e.getEdad(),e.getFechanacimiento().toString(), e.getFecharegistro().toString(), e.getNomimagen(), e.getPuntaje()}; 
               table_model_eventos2.addRow(data);
            }else if((Integer.parseInt(e.getEdad()))>24&&(Integer.parseInt(e.getEdad()))<=50){
                String[] data = {Integer.toString(e.getId()), e.getCedula(),e.getNombre(), e.getApellido(), e.getEdad(),e.getFechanacimiento().toString(), e.getFecharegistro().toString(), e.getNomimagen(), e.getPuntaje()}; 
               table_model_eventos3.addRow(data);
            }
                
            
            
            
            
        }
        
        
        /*for(Evento e: lista_eventos)
        {
            String[] data = {Integer.toString(e.getId()), e.getCedula(),e.getNombre(), e.getApellido(), e.getEdad(),e.getFechanacimiento().toString(), e.getFecharegistro().toString(), e.getNomimagen(), e.getPuntaje()};
            
            table_model_eventos.addRow(data);
        }*/
       




}
}
