/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto__c3;

import java.awt.Color;
import javax.swing.JFrame;

/**
 *
 * @author rojas
 */
public class Registro extends javax.swing.JFrame {
javax.swing.JFrame padre;
    /**
     * Creates new form Registro
     */
    public Registro() {
        initComponents();
        this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        this.setVisible(false);
        
       
    }
    public void recibir (javax.swing.JFrame padre1){
        this.padre=padre1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jugador1_nom = new javax.swing.JTextField();
        jugador4_nom = new javax.swing.JTextField();
        jugador2_nom = new javax.swing.JTextField();
        jugador3_nom = new javax.swing.JTextField();
        jugador1_edad = new javax.swing.JTextField();
        jugador4_edad = new javax.swing.JTextField();
        jugador2_edad = new javax.swing.JTextField();
        jugador3_edad = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jugador1_ced = new javax.swing.JTextField();
        jugador4_ced = new javax.swing.JTextField();
        jugador2_ced = new javax.swing.JTextField();
        jugador3_ced = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jugador1_ap = new javax.swing.JTextField();
        jugador4_ap = new javax.swing.JTextField();
        jugador2_ap = new javax.swing.JTextField();
        jugador3_ap = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");
        setMaximumSize(new java.awt.Dimension(590, 300));
        setMinimumSize(new java.awt.Dimension(590, 300));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 0, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 255, 255));
        jLabel2.setText("registro de jugadores ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(140, 10, 460, 90);
        getContentPane().add(jugador1_nom);
        jugador1_nom.setBounds(110, 150, 70, 20);
        getContentPane().add(jugador4_nom);
        jugador4_nom.setBounds(110, 240, 70, 20);
        getContentPane().add(jugador2_nom);
        jugador2_nom.setBounds(110, 180, 70, 20);
        getContentPane().add(jugador3_nom);
        jugador3_nom.setBounds(110, 210, 70, 20);

        jugador1_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1_edadActionPerformed(evt);
            }
        });
        getContentPane().add(jugador1_edad);
        jugador1_edad.setBounds(380, 150, 70, 20);
        getContentPane().add(jugador4_edad);
        jugador4_edad.setBounds(380, 240, 70, 20);
        getContentPane().add(jugador2_edad);
        jugador2_edad.setBounds(380, 180, 70, 20);
        getContentPane().add(jugador3_edad);
        jugador3_edad.setBounds(380, 210, 70, 20);

        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("nombre jugador 4");
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 100));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 240, 85, 14);

        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("nombre jugador 1");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 150, 85, 14);

        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("nombre jugador 2");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 85, 14);

        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("nombre jugador 3");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 210, 85, 14);

        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("edad");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(340, 180, 34, 14);

        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("edad");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(340, 210, 34, 14);

        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("edad");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(340, 240, 34, 14);

        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("edad");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(340, 150, 34, 14);

        jugador1_ced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jugador1_cedActionPerformed(evt);
            }
        });
        getContentPane().add(jugador1_ced);
        jugador1_ced.setBounds(510, 150, 70, 20);
        getContentPane().add(jugador4_ced);
        jugador4_ced.setBounds(510, 240, 70, 20);
        getContentPane().add(jugador2_ced);
        jugador2_ced.setBounds(510, 180, 70, 20);
        getContentPane().add(jugador3_ced);
        jugador3_ced.setBounds(510, 210, 70, 20);

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("cedula");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(470, 180, 41, 14);

        jLabel12.setForeground(java.awt.Color.white);
        jLabel12.setText("cedula");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(470, 210, 41, 14);

        jLabel13.setForeground(java.awt.Color.white);
        jLabel13.setText("cedula");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(470, 240, 41, 14);

        jLabel14.setForeground(java.awt.Color.white);
        jLabel14.setText("cedula");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(470, 150, 41, 14);

        jButton1.setText("registarse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(60, 280, 81, 23);

        jButton2.setText("cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(170, 280, 73, 23);

        jLabel15.setForeground(java.awt.Color.white);
        jLabel15.setText("apellido");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(200, 150, 36, 14);

        jLabel16.setForeground(java.awt.Color.white);
        jLabel16.setText("apellido");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(200, 180, 36, 14);

        jLabel17.setForeground(java.awt.Color.white);
        jLabel17.setText("apellido");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(200, 210, 36, 14);
        getContentPane().add(jugador1_ap);
        jugador1_ap.setBounds(250, 150, 70, 20);
        getContentPane().add(jugador4_ap);
        jugador4_ap.setBounds(250, 240, 70, 20);
        getContentPane().add(jugador2_ap);
        jugador2_ap.setBounds(250, 180, 70, 20);
        getContentPane().add(jugador3_ap);
        jugador3_ap.setBounds(250, 210, 70, 20);

        jLabel18.setForeground(java.awt.Color.white);
        jLabel18.setText("apellido");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(200, 240, 36, 14);

        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(500, 280, 0, 0);

        jLabel22.setForeground(java.awt.Color.white);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/milky-way-2695569__340_1.jpg"))); // NOI18N
        jLabel22.setMaximumSize(new java.awt.Dimension(800, 800));
        jLabel22.setMinimumSize(new java.awt.Dimension(800, 800));
        jLabel22.setPreferredSize(new java.awt.Dimension(800, 800));
        getContentPane().add(jLabel22);
        jLabel22.setBounds(0, -230, 800, 800);

        getAccessibleContext().setAccessibleParent(this);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jugador1_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador1_edadActionPerformed

    private void jugador1_cedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jugador1_cedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jugador1_cedActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 jugador1_ap.setText("");
 jugador1_ced.setText("");
 jugador1_edad.setText("");
 jugador1_nom.setText("");
 jugador2_ap.setText("");
 jugador2_ced.setText("");
 jugador2_edad.setText("");
 jugador2_nom.setText("");
 jugador3_ap.setText("");
 jugador3_ced.setText("");
 jugador3_edad.setText("");
 jugador3_nom.setText("");
 jugador4_ap.setText("");
 jugador4_ced.setText("");
 jugador4_edad.setText("");
 jugador4_nom.setText("");
 this.setVisible(false);

 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
 jugador1_ap.setText("");
 jugador1_ced.setText("");
 jugador1_edad.setText("");
 jugador1_nom.setText("");
 jugador2_ap.setText("");
 jugador2_ced.setText("");
 jugador2_edad.setText("");
 jugador2_nom.setText("");
 jugador3_ap.setText("");
 jugador3_ced.setText("");
 jugador3_edad.setText("");
 jugador3_nom.setText("");
 jugador4_ap.setText("");
 jugador4_ced.setText("");
 jugador4_edad.setText("");
 jugador4_nom.setText("");
 this.setVisible(false);



    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
        
        
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jugador1_ap;
    private javax.swing.JTextField jugador1_ced;
    private javax.swing.JTextField jugador1_edad;
    private javax.swing.JTextField jugador1_nom;
    private javax.swing.JTextField jugador2_ap;
    private javax.swing.JTextField jugador2_ced;
    private javax.swing.JTextField jugador2_edad;
    private javax.swing.JTextField jugador2_nom;
    private javax.swing.JTextField jugador3_ap;
    private javax.swing.JTextField jugador3_ced;
    private javax.swing.JTextField jugador3_edad;
    private javax.swing.JTextField jugador3_nom;
    private javax.swing.JTextField jugador4_ap;
    private javax.swing.JTextField jugador4_ced;
    private javax.swing.JTextField jugador4_edad;
    private javax.swing.JTextField jugador4_nom;
    // End of variables declaration//GEN-END:variables
}
