/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto__c3;

/**
 *
 * @author rojas
 */
public class tablero_juego extends javax.swing.JFrame {
    Movimientos_rojas roja;
    Movimientos_azules azul;
    Movimientos_verdes verde;
    Movimientos_amarillas amarillo;
    public tablero_juego() {
        initComponents();    
        iniciar();
    }
    void iniciar(){
      roja= new Movimientos_rojas(f_roja,0);
      roja.start();
      azul= new Movimientos_azules(f_azul,0);
      azul.start();
      verde = new Movimientos_verdes(f_verde,0);
      verde.start();
      amarillo = new Movimientos_amarillas(f_amarilla,0);
      amarillo.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        f_azul = new javax.swing.JLabel();
        f_roja = new javax.swing.JLabel();
        f_amarilla = new javax.swing.JLabel();
        f_verde = new javax.swing.JLabel();
        panel_juego1 = new proyecto__c3.Panel_juego();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(837, 640));
        getContentPane().setLayout(null);

        f_azul.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/peque5.png"))); // NOI18N
        f_azul.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                f_azulMouseDragged(evt);
            }
        });
        getContentPane().add(f_azul);
        f_azul.setBounds(480, 240, 20, 20);

        f_roja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/peque2.png"))); // NOI18N
        f_roja.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                f_rojaMouseDragged(evt);
            }
        });
        getContentPane().add(f_roja);
        f_roja.setBounds(480, 220, 20, 20);

        f_amarilla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/peque3.png"))); // NOI18N
        f_amarilla.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                f_amarillaMouseDragged(evt);
            }
        });
        getContentPane().add(f_amarilla);
        f_amarilla.setBounds(480, 180, 20, 20);

        f_verde.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto_c3/imagen/peque4.png"))); // NOI18N
        f_verde.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                f_verdeMouseDragged(evt);
            }
        });
        getContentPane().add(f_verde);
        f_verde.setBounds(480, 200, 20, 20);
        getContentPane().add(panel_juego1);
        panel_juego1.setBounds(0, 0, 600, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void f_amarillaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_amarillaMouseDragged
       
    }//GEN-LAST:event_f_amarillaMouseDragged

    private void f_verdeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_verdeMouseDragged
 
    }//GEN-LAST:event_f_verdeMouseDragged

    private void f_rojaMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_rojaMouseDragged

    }//GEN-LAST:event_f_rojaMouseDragged

    private void f_azulMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_f_azulMouseDragged

    }//GEN-LAST:event_f_azulMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tablero_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tablero_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tablero_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tablero_juego.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tablero_juego().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel f_amarilla;
    private javax.swing.JLabel f_azul;
    private javax.swing.JLabel f_roja;
    private javax.swing.JLabel f_verde;
    private proyecto__c3.Panel_juego panel_juego1;
    // End of variables declaration//GEN-END:variables
}
